travis:
  secure:
    BINSTAR_TOKEN: fzvZ2Zc3+sLNuv8V4yYQahpJuImucJ6qbBTGk/W3HmurFirfd0nMgAzGxylWIO3D4Kar+Pq8wnDE8FCQpi1lAFvAjKuWCGFWkYJrYav3VP0QGKRDNEmXZ5qabX3LpNZKACyRP5Q6c6hTfz+ASB6+j6XvmcZ4OWB42NhTawM1Ryh25760oOejnJUEMGa1nr9ih8Pfz2DpHMpFZhGnDTqJV7IbO4E0CTueZxgZ4gSAcDSIoat4eClpiUyZdS7jxBoMSJQBOGDc2HWnwyPSeeBZUlIclCV3MWa77kpv2NkqUObbu0xj5SFyhSkneQSmTf9R2bpnV41cDqEcf3YJdhZiCRwAV2S/P9XPJdK0HWjsjaEY8joYr5/7xRGAYWAOOvavQpPQQ/KxC6SjCAAWa3PAL3Op3hq//NgAoKm9fsO5bYBnm3HpIx/VeWLUiRyQjatk6yrZokptF8j73lFe1QxC+JzYD3+HFReh13QN95Do0LGyczRCLQne4kyDbwIuBlTEcJjHRESQU3BpVrcB3/t3w8HrPHMTAV5huATPU6Md+g01fQwX5yek0xs7EkzRkAOGTBis89GusehcEYUaPHW3Ye/R2rm0vqTDIjzVeRwNmw5pSGS97WGe8YsoFAcNoVAAvewHh998smPOPIDvW+i0hZU1ZoFcx00Z+TzEUahmpxE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
