appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: CrDA6GTbajfkLFrj6IpeebdPeBtWyIrdo1tX+tv0H95f7dJ3rr0P8c+ZtkgFcOjw2oC7Lvoa4YcvEVc5q4Nbs8/HAzXQMHY+/RhZE7ceAfP32REH4FvEhhOGFW/AX3PfHI/bQ0KheH21JuOAbc9OYVmpDopwIarhrWHN6C3FzLd+h1ASxNItPqd053O0uQY95RV10kGlRGAxI9V8c2UlEKfw1DDJ3NTIcydLY7PmsN8CxI19OGfZAh5EqBgZ1OpoVQHjhSx+p/TYTAMqWRkPLMegQx90gRO11KB31/D6xQMBVUto3ZX3HjXy0h6AGljdThjlxo+mJuKcGQ8qVvkeu2Bg2t++3f+sbYPPnYbRXX1zEJJIzSyXWrPWAbhEPSDxHT7ZgK2hzKin8ImJDnBRR6E4pQAEwqkj+1sJaDoQ06nf9fw7PjmtUWDWHobPiJuPXTytujidOIlEKaFv7TpRP7lgYZk11TjCL7plPR8e+nB9rFCCUmdALZYpzonNp6ztfkOyPoU5YBgT4aj7MpvqOht9F5deCHsLy37oa6sQA/OCDgBZIfEGvD2MeUHfqhbJLK7fzTFb7CeWHy9rOxCOOLrC6WJT4tSRqmVwqi9B1WO0AyiZ/tW9D/TmiqoHZeKSS2TDguk/a9M5q1R1Ranfb59G8gIAff6pszS+331q3YA=}
provider:
  win: azure
